### PR TITLE
Add Debug trait implementation to struct Animation.

### PR DESCRIPTION
**Pull request by cireu**

### CODE REVIEW

**Comment by msrd0** [comment]
Why do you need this? I'd assume printing a pointer isn't necessarily helpful for debugging.

**Comment by cireu** [comment]
If we don't have this, struct contains `Animation` cannot use `#[derive(Debug)]`

**Comment by msrd0** [comment]
Do you think a more abstract implementation like this one would be sufficient for your use case? https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9af39eac8f9e0d0445c25a83470ca3d5

**Comment by cireu** [comment]
Hmm, `Animation { .. }` is OK, but IMO a extra pointer address information is not bad.

**Comment by msrd0** [comment]
From an API perspective, I want no way of anyone to obtain that adress so I don't have to worry about them using it to make the API unsound. For example, an application could extract the adress from the debug string and call the rlottie's destructor, making all further calls to `Animation`, including its `Drop` impl, unsound.

In short, giving the adress to anyone makes it impossible to uphold safety prerequisites which are necessary for the `unsafe` codeblocks used in the crate.

**Comment by cireu** [comment]
OK :) I'd glad to see your code example above being merged

**Comment by msrd0** [comment]
I just released it in 0.3.1

**Pull request closed without merging**
